### 卷积神经网络

In [1]:
import torch

In [12]:
import torch.nn.functional as F

In [5]:
# 图像输入
input = torch.tensor([[1, 2, 0, 3, 1],
                      [0, 1, 2, 3, 1],
                      [1, 2, 1, 0, 0],
                      [5, 2, 3, 1, 1],
                      [2, 1, 0, 1, 1]])

In [4]:
# 卷积核
kernel = torch.tensor([[1, 2, 1],
                       [0, 1, 0],
                       [2, 1, 0]])

In [6]:
input.shape

torch.Size([5, 5])

In [7]:
kernel.shape

torch.Size([3, 3])

为了输入进模型，需要改变输入的形状为（batch_size,通道数（灰度还是RGB），图像尺寸（5*5））

In [8]:
input = torch.reshape(input,(1,1,5,5))

In [9]:
kernel = torch.reshape(kernel,(1,1,3,3))

In [10]:
input.shape

torch.Size([1, 1, 5, 5])

In [11]:
kernel.shape

torch.Size([1, 1, 3, 3])

输入卷积模型

In [16]:
# stride表示卷积核移动的步长
output = F.conv2d(input,kernel,stride=1)

In [17]:
output

tensor([[[[10, 12, 12],
          [18, 16, 16],
          [13,  9,  3]]]])

In [14]:
output2 = F.conv2d(input,kernel,stride=2)

In [15]:
output2

tensor([[[[10, 12],
          [13,  3]]]])

padding=1 参数，给图像周围填充一圈0，使得卷积操作后图像的尺寸不变

In [18]:
# padding=1，图像还是（5*5）
output3 = F.conv2d(input,kernel,stride=1,padding=1)

In [19]:
output3

tensor([[[[ 1,  3,  4, 10,  8],
          [ 5, 10, 12, 12,  6],
          [ 7, 18, 16, 16,  8],
          [11, 13,  9,  3,  4],
          [14, 13,  9,  7,  4]]]])