### 非线性激活函数,RELU,Sigmoid

In [23]:
import torch
import torchvision
from torch import nn
from torch.nn import Conv2d
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter

In [24]:
from torch.nn import ReLU
from torch.nn import Sigmoid

In [25]:
dataset = torchvision.datasets.CIFAR10(root="./dataset",train=False,transform=torchvision.transforms.ToTensor())

In [26]:
dataloader = DataLoader(dataset,batch_size=64)

In [27]:
writer = SummaryWriter("logs")

模型

In [40]:
class TuDui(nn.Module):
    def __init__(self):
        super(TuDui,self).__init__()
        self.relu = ReLU()
        self.sigmoid = Sigmoid()

    def forward(self,input,activate):
        if(activate == 'ReLU'):
            output = self.relu(input)
        if(activate == 'Sigmoid'):
            output = self.sigmoid(input)
        return output


In [41]:
tudui = TuDui()

In [42]:
input = torch.tensor([[1, -0.5],
                      [-1, 3]])

input = torch.reshape(input, (-1, 1, 2, 2))

In [43]:
output = tudui.forward(input,'Sigmoid')

In [44]:
output

tensor([[[[0.7311, 0.3775],
          [0.2689, 0.9526]]]])

In [45]:
output = tudui.forward(input,'ReLU')

In [46]:
output

tensor([[[[1., 0.],
          [0., 3.]]]])

数据集

In [54]:
for data in dataloader:
    imgs,targets = data
    # print(imgs)
    # output_relu = tudui.forward(imgs,'ReLU')
    # print(output_relu)

    output_sigmoid = tudui.forward(imgs,'Sigmoid')
    print(output_sigmoid)

tensor([[[[0.6501, 0.6510, 0.6563,  ..., 0.6312, 0.6211, 0.6118],
          [0.6448, 0.6439, 0.6510,  ..., 0.6303, 0.6202, 0.6146],
          [0.6439, 0.6439, 0.6501,  ..., 0.6330, 0.6248, 0.6155],
          ...,
          [0.5663, 0.5411, 0.5304,  ..., 0.5372, 0.5127, 0.5391],
          [0.5595, 0.5479, 0.5343,  ..., 0.5255, 0.5284, 0.5196],
          [0.5527, 0.5547, 0.5440,  ..., 0.5235, 0.5333, 0.5206]],

         [[0.6081, 0.6071, 0.6118,  ..., 0.5921, 0.5883, 0.5826],
          [0.6081, 0.6062, 0.6099,  ..., 0.5921, 0.5883, 0.5854],
          [0.6062, 0.6053, 0.6071,  ..., 0.5949, 0.5921, 0.5864],
          ...,
          [0.6192, 0.5968, 0.5854,  ..., 0.5940, 0.5624, 0.5826],
          [0.6118, 0.5987, 0.5826,  ..., 0.5797, 0.5797, 0.5624],
          [0.6034, 0.6015, 0.5864,  ..., 0.5749, 0.5816, 0.5653]],

         [[0.5479, 0.5459, 0.5498,  ..., 0.5352, 0.5352, 0.5323],
          [0.5498, 0.5391, 0.5440,  ..., 0.5304, 0.5313, 0.5333],
          [0.5459, 0.5323, 0.5352,  ..., 0

由于图像中没有负值，所以Relu函数，不改变图像

In [39]:
step = 0
for data in dataloader:
    imgs,targets = data
    writer.add_images("source",imgs,step)
    output_relu = tudui.forward(imgs,'ReLU')
    writer.add_images("ReLU",output_relu,step)
    output_sigmoid = tudui.forward(imgs,'Sigmoid')
    writer.add_images("Sigmoid",output_sigmoid,step)
    step += 1

In [38]:
writer.close()