## 3.1 张量(Tensors)的初始化

In [16]:
import torch
import numpy as np

### 1.从数据初始化

In [17]:
data = [[1.,2],[3,4]]

In [18]:
x_data = torch.tensor(data)

In [19]:
x_data

tensor([[1., 2.],
        [3., 4.]])

### 2.从numpy初始化

In [20]:
numpy_data = np.array(data)

In [21]:
numpy_data

array([[1., 2.],
       [3., 4.]])

In [22]:
torch_data = torch.from_numpy(numpy_data)

In [23]:
torch_data

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

### 3.从另外一个张量（Tensors）获取

全1张量，形状大小和原张量相同

In [24]:
one_data = torch.ones_like(torch_data)

In [25]:
one_data

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

随机数，形状大小和原张量相同

In [27]:
rand_data = torch.rand_like(torch_data)

In [28]:
rand_data

tensor([[0.2931, 0.2372],
        [0.0511, 0.8270]], dtype=torch.float64)

### 4.使用随机值或常量值

In [36]:
shape = (2,3)

In [37]:
rand_torch = torch.rand(shape)

In [38]:
rand_torch

tensor([[0.3510, 0.6156, 0.4650],
        [0.4190, 0.3984, 0.7252]])

In [39]:
ones_torch = torch.ones(shape)

In [40]:
ones_torch

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [41]:
zeros_torch = torch.zeros(shape)

In [42]:
zeros_torch

tensor([[0., 0., 0.],
        [0., 0., 0.]])