## 3.3 张量(Tensors)的操作

In [2]:
import torch

cuda不能用

In [3]:
if torch.cuda.is_available():
    tensor = torch.to('cuda')
    print(f"Device tensor is stored on: {tensor.device}")

In [4]:
torch.cuda.is_available()

False

### 索引和切片

In [5]:
tensor = torch.ones(4,4)

In [6]:
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
tensor[:,:2]

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [8]:
tensor[:,1] = 0

In [9]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

### 连接张量

In [10]:
# dim=0代表行，dim=1代表列
t1 = torch.cat([tensor,tensor],dim=1) 

In [11]:
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.]])

In [12]:
t2 = torch.cat([tensor,tensor],dim=0)

In [13]:
t2

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

### Tensor乘法

In [14]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

点乘

In [15]:
tensor * 2

tensor([[2., 0., 2., 2.],
        [2., 0., 2., 2.],
        [2., 0., 2., 2.],
        [2., 0., 2., 2.]])

一维向量乘

In [16]:
# 行向量乘,原tensor每一行乘以相应倍数
row = torch.tensor([1,2,3,4])
tensor * row

tensor([[1., 0., 3., 4.],
        [1., 0., 3., 4.],
        [1., 0., 3., 4.],
        [1., 0., 3., 4.]])

In [22]:
# 列向量乘，原tensor每一列乘以相应倍数
col = torch.tensor([[1.],[2.],[3.],[4.]])
tensor * col

tensor([[1., 0., 1., 1.],
        [2., 0., 2., 2.],
        [3., 0., 3., 3.],
        [4., 0., 4., 4.]])

In [26]:
row = row.reshape((4,1))

In [27]:
col == row

tensor([[True],
        [True],
        [True],
        [True]])

矩阵点积，对应位相乘

In [18]:
mutulTensor = tensor.mul(tensor)

In [19]:
mutulTensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [20]:
a = torch.tensor([[1,2],[3,4]])

In [28]:
a * a

tensor([[ 1,  4],
        [ 9, 16]])

矩阵相乘

In [29]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [30]:
torch.mm(tensor,tensor)

tensor([[3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.]])

torch.matmul   torch.mm的broadcast版本

In [31]:
a = torch.ones(3,4)

In [32]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
b = torch.ones(5,4,2)

In [34]:
b

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])

广播机制 (3,4)矩阵和5个(4,2)矩阵相乘

In [35]:
torch.matmul(a,b)

tensor([[[4., 4.],
         [4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.],
         [4., 4.]]])