## 3.4 使用numpy作为桥接

In [1]:
import torch

张量到numpy

In [2]:
a = torch.tensor([1,2,3,4])

In [3]:
a

tensor([1, 2, 3, 4])

In [5]:
b = a.numpy()

In [6]:
b

array([1, 2, 3, 4], dtype=int64)

numpy到张量

In [7]:
c = torch.from_numpy(b)

In [8]:
c

tensor([1, 2, 3, 4])